### PR TITLE
initial tested version

### PR DESCRIPTION
**Pull request by thelamer**
This app is not only useful in research but in the OSINT space. Tested the basics like the connection between the chrome extension and the app and sync. 
It uses tint2 because bouncing from the web browser to the app is a must.

### CODE REVIEW

**Comment by thelamer** [comment]
Linking https://github.com/linuxserver/docker-templates/pull/307 and Discouse https://discourse.linuxserver.io/t/zotero-kasmvnc-client/8543/7

**Comment by thelamer** [comment]
Approved by initial requester

**Review by drizuid — APPROVED** [review]
dont forget cstate

**Comment by thelamer** [comment]
> dont forget cstate
Linking https://github.com/linuxserver/cstate/pull/208

**Pull request merged**
